// File generated by FlutterFire CLI.
// ignore_for_file: type=lint
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for macos - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      case TargetPlatform.windows:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for windows - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyC6Bv-Vb6p5RmGOIR0mC8KyI9Obq4Q31DI',
    appId: '1:324573076676:web:d28ff343a4cf9fe78a3d91',
    messagingSenderId: '324573076676',
    projectId: 'ukihome-sample',
    authDomain: 'ukihome-sample.firebaseapp.com',
    storageBucket: 'ukihome-sample.appspot.com',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyBpQJTAv_9RxwqhS-aRPyYqM03cJTAEBZU',
    appId: '1:324573076676:android:6f07586987c59a198a3d91',
    messagingSenderId: '324573076676',
    projectId: 'ukihome-sample',
    storageBucket: 'ukihome-sample.appspot.com',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyDqKfKm6C0dBdYQ8CWblmC8zGO-WdV5Vfg',
    appId: '1:324573076676:ios:9f33884d981bdc308a3d91',
    messagingSenderId: '324573076676',
    projectId: 'ukihome-sample',
    storageBucket: 'ukihome-sample.appspot.com',
    iosBundleId: 'com.ukihome.kaimonoList',
  );
}
