// File generated by FlutterFire CLI.
// ignore_for_file: type=lint
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for macos - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      case TargetPlatform.windows:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for windows - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyBdhKKIUvOj6dvhi-_kLGNDlvIwRsE7rOE',
    appId: '1:578807791493:web:5ec4412c29806277b50eec',
    messagingSenderId: '578807791493',
    projectId: 'kaimono-list-7174f',
    authDomain: 'kaimono-list-7174f.firebaseapp.com',
    storageBucket: 'kaimono-list-7174f.appspot.com',
    measurementId: 'G-LGC6PNVN6G',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyC3Uv-4Nf2WU9TZSLA27h8HSrN5KSjALcg',
    appId: '1:578807791493:android:eec99f6816dab9bab50eec',
    messagingSenderId: '578807791493',
    projectId: 'kaimono-list-7174f',
    storageBucket: 'kaimono-list-7174f.appspot.com',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyAVzxr9RtqdUtsIHoD4lf8409WTgliHZyQ',
    appId: '1:578807791493:ios:7e51c675bf185419b50eec',
    messagingSenderId: '578807791493',
    projectId: 'kaimono-list-7174f',
    storageBucket: 'kaimono-list-7174f.appspot.com',
    iosBundleId: 'com.ukihome.kaimonoList',
  );
}
