name: "scripts"
description: "A collection of scripts for the Flutter project"

environment: { sdk: ^3.5.3 }

dependencies:
  collection: ^1.19.0
  recase: ^4.1.0

dev_dependencies:
  very_good_analysis: ^6.0.0
